name: Package for github

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.10.5
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: |
          pnpm build:orm
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish
        run: |
          old_version="$(jq -r .version package.json)"
          version="$old_version-$(git rev-parse --short HEAD)"
          echo "Publishing @${{github.repository_owner}}/drizzle-orm using version $version"
          npm pkg set 'name'='@${{github.repository_owner}}/drizzle-orm'
          npm pkg set 'repository.url'='git+https://github.com/${{github.repository_owner}}/drizzle-orm.git'
          npm pkg delete 'scripts.pack'
          npm pkg delete 'scripts.publish'
          npm version $version
          npm publish --provenance --access public
        working-directory: ./drizzle-orm/dist
        shell: bash